In [18]:
import numpy as np
from sklearn.tree import DecisionTreeRegressor
import TataSteel as input_data

Load physics data
=================

In [19]:
train_dir = '/users/TeamSteel/TATA_Steel_Project/TATA_Steel_Project/Data'
data_sets = input_data.read_data_sets(train_dir,'physics_input_data.pkl')
training_data = data_sets.train
validation_data = data_sets.validation
test_data = data_sets.test


  Load the training data
-------------------------

In [20]:
train_inp, train_tgt = training_data._inputs, training_data._targets

Train decision tree model
=========================

In [21]:
model = DecisionTreeRegressor()
model.fit(train_inp,train_tgt)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, presort=False, random_state=None,
           splitter='best')

Evaluate model
==============

In [22]:
def eval_model(model, data):
    """
    Evaluates a trained model for a given dataset
    
    Inputs:
           model = any sklearn machine learning model
           data  = dataset structure with the inputs and targets
    Outputs:
           relative_RMSE = (Root Mean Squared Error / Mean Values of the Targets)
    """
    inputs = data._inputs
    targets = data._targets
    predictions = model.predict(inputs)
    squared_error = np.square(targets-predictions)
    
    MSE = np.mean(squared_error, axis=0)
    RMSE = np.sqrt(MSE)
    
    mean_target = np.mean(targets, axis=0)
    relative_RMSE = np.divide(RMSE, mean_target)
    return relative_RMSE

a) Training RMSE
-------------

In [23]:
train_RMSE = eval_model(model,training_data)

In [24]:
train_RMSE

matrix([[ 0.,  0.,  0.]])

b) Validation RMSE
---------------

In [25]:
val_RMSE = eval_model(model,validation_data)

In [26]:
val_RMSE

matrix([[ 0.19211773,  0.24039623,  0.22404256]])

c) Test RMSE
---------

In [27]:
test_RMSE = eval_model(model, test_data)

In [28]:
test_RMSE

matrix([[ 0.17235117,  0.23467496,  0.22285221]])

Load chemistry data
===================

In [12]:
train_dir = '/users/TeamSteel/TATA_Steel_Project/TATA_Steel_Project/Data'
data_sets = input_data.read_data_sets(train_dir,'chemistry_input_data.pkl')
training_data = data_sets.train
validation_data = data_sets.validation
test_data = data_sets.test

  Load the training data
-------------------------

In [13]:
train_inp, train_tgt = training_data._inputs, training_data._targets

Train decision tree model
=========================

In [14]:
model = DecisionTreeRegressor()
model.fit(train_inp,train_tgt)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, presort=False, random_state=None,
           splitter='best')

Evaluate model
==============

a) Training RMSE
-------------

In [15]:
train_RMSE = eval_model(model,training_data)
train_RMSE

matrix([[ 0.04730532,  0.03366926,  0.02037684]])

b) Validation RMSE
---------------

In [16]:
val_RMSE = eval_model(model,validation_data)
val_RMSE

matrix([[ 0.12436527,  0.07567543,  0.05008004]])

c) Test RMSE
---------

In [17]:
test_RMSE = eval_model(model, test_data)
test_RMSE

matrix([[ 0.09010596,  0.08500106,  0.05819921]])